
#include <i2clcd.h>
#include "m_i2c.h"
#include <delay.h>

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroeElektronika 2011
//http://www.mikroe.com

//HD44780 Alpha Numeric Character Set - FontName : RTC5x8
//HD44780 Alpha Numeric Character Set - FontSize : 5 x 8

const uint8_t RTC5x8[] = {
    0x08, 0x14, 0x08, 0x03, 0x04, 0x07, 0x04, 0x04, // Code for char num #0 Faranheit
    0x08, 0x14, 0x08, 0x03, 0x04, 0x04, 0x03, 0x00, // Code for char num #1 Celcius
    0x04, 0x0A, 0x0E, 0x0A, 0x00, 0x1A, 0x15, 0x15, // Code for char num #2 AM
    0x04, 0x0A, 0x0C, 0x08, 0x00, 0x1A, 0x15, 0x15, // Code for char num #3 PM
    0x0C, 0x12, 0x12, 0x0C, 0x00, 0x00, 0x00, 0x00, // Code for char num #4 Degrees
    0x00, 0x01, 0x01, 0x05, 0x05, 0x15, 0x15, 0x00, // Code for char num #5 Bar
    0x00, 0x15, 0x0E, 0x04, 0x04, 0x04, 0x04, 0x00, // Code for char num #6 Antenna
    0x0E, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x00 // Code for char num #7 Battery Full
};

const uint8_t SPECIAL_1_5x8[] = {
    0x02, 0x05, 0x01, 0x12, 0x07, 0x13, 0x14, 0x13, // Code for char num #0 - i2c
    0x04, 0x0E, 0x0E, 0x0E, 0x0E, 0x1F, 0x00, 0x04, // Code for char num #1 - Bell
    0x1C, 0x14, 0x1C, 0x0E, 0x0B, 0x0E, 0x03, 0x02, // Code for char num #2 - Off
    0x1C, 0x14, 0x1C, 0x00, 0x12, 0x1A, 0x16, 0x00, // Code for char num #3 - On
    0x01, 0x03, 0x05, 0x09, 0x09, 0x0B, 0x1B, 0x18, // Code for char num #4 - Music
    0x00, 0x0A, 0x1F, 0x1F, 0x1F, 0x0E, 0x04, 0x00, // Code for char num #5 - Heart
    0x04, 0x0E, 0x1F, 0x04, 0x04, 0x04, 0x04, 0x00, // Code for char num #6 - Up
    0x04, 0x04, 0x04, 0x04, 0x1F, 0x0E, 0x04, 0x00 // Code for char num #7 - Down
};

const char CELSIUS[]={
    0x08, 0x14, 0x08, 0x03, 0x04, 0x04, 0x03, 0x00 // Code for char num  - CELSIUS
};

const char UP[]={
    0x04, 0x0E, 0x1F, 0x04, 0x04, 0x04, 0x04, 0x00 // Code for char num  - Up
};

const char DOWN[]={
    0x04, 0x04, 0x04, 0x04, 0x1F, 0x0E, 0x04, 0x00 // Code for char num  - Down
};

const char ENTER_KEY[] = {
	0b00001,
	0b00001,
	0b00101,
	0b01101,
	0b11111,
	0b01100,
	0b00100,
	0b00000
};
//-----------------------Function Implementation-------------------------
/*
 * Define a special custom character to LCD
 * spclchar = array that define the special character
 * charpos = address space in CGRAM to store the character from 0 to 7
 * Character generator solution online at http://mikeyancey.com/hamcalc/lcd_characters.php
 */
void LCDI2C_DefineSpecialChars(const char* spclchar, uint8_t charpos)
{
    int8_t idx = 8;
    LCDI2C_Write(LCD_SETCGRAMADDR | (charpos * 8), 0); // Set CGRAM to first Special font space
    while (idx--)
        LCDI2C_Write(*spclchar++, Rs);
    LCDI2C_ReturnHome();
}

void LCDI2C_InitHD44780CustomChars(void)
{
    char i;
    LCDI2C_Write(LCD_SETCGRAMADDR, 0);
    for (i = 0; i <= 63; i++)
        LCDI2C_Write(RTC5x8[i], Rs);
    LCDI2C_ReturnHome();
}

void LCDI2C_Init(void){
    i2c_init(1000000);
    //first init string
    i2c_send_byte(0x3C,LCD_I2C);
    dly_ms(10);
    i2c_send_byte(0x38,LCD_I2C);
    dly_ms(10);
#ifdef DEBUGGING
    i2c_print_err();
    printf("firs OK\n");
#endif

    //second init string
    i2c_send_byte(0x3C,LCD_I2C);
    dly_ms(10);
    i2c_send_byte(0x38,LCD_I2C);
    dly_ms(10);

#ifdef DEBUGGING
    i2c_print_err();
#endif

    //third init string
    i2c_send_byte(0x3C,LCD_I2C);
    dly_ms(10);
    i2c_send_byte(0x38,LCD_I2C);
    dly_ms(10);

    //fourth init string
    // 4 bits mode, only per indications of initializaton
    i2c_send_byte(0x2C,LCD_I2C);
    dly_ms(10);
    i2c_send_byte(0x28,LCD_I2C);
    dly_ms(10);


#ifdef DEBUGGING
    i2c_print_err();
#endif

    // 4 bits mode, only per indications of initializaton
    LCDI2C_Write(LCD_FUNCTIONSET | LCD_5x8DOTS | LCD_4BITMODE | LCD_2LINE , 0 );

    // Display OFF
    LCDI2C_Write(LCD_DISPLAYCONTROL | LCD_DISPLAYOFF , 0 );

    // Display ON
    LCDI2C_Write(LCD_DISPLAYCONTROL | LCD_DISPLAYON , 0 );

    // Clear Display,
    LCDI2C_Write(LCD_CLEARDISPLAY , 0 );

    // Entry Mode Set 
    LCDI2C_Write(LCD_ENTRYMODESET | LCD_ENTRYLEFT , 0 );

    LCDI2C_InitHD44780CustomChars();
}

void LCDI2C_DisplayOnOff( char status ){
    if (status){
            LCDI2C_Write(LCD_DISPLAYCONTROL | LCD_DISPLAYON , 0 );
    }
    else{
            LCDI2C_Write(LCD_DISPLAYCONTROL | LCD_DISPLAYOFF , 0 );
    }
}

void LCDI2C_CursorOnOff( char status ){
    if (status){
            LCDI2C_Write(LCD_DISPLAYCONTROL | LCD_CURSORON , 0 );
    }
    else{
            LCDI2C_Write(LCD_DISPLAYCONTROL | LCD_CURSOROFF , 0 );
    }
}


void LCDI2C_Write(unsigned char data , unsigned char RS){

//****************************Data upper bits-Nibble***************************
    lcd_buffer = ((data & 0xf0) | RS | LCD_BACKLIGHT);	//upper nibble
    lcd_buffer &= ~En;
    //***************************
    i2c_send_byte(lcd_buffer,LCD_I2C);
#ifdef DEBUGGING
    i2c_print_err();
    printf("On Write  first Data Buffer has: 0x%02X\n", lcd_buffer);
#endif
//***********
    lcd_buffer |= En;
    i2c_send_byte(lcd_buffer,LCD_I2C);
#ifdef DEBUGGING
    i2c_print_err();
    printf("On Write  second Data Buffer has: 0x%02X\n", lcd_buffer);
#endif
//***********
    lcd_buffer &= ~En;
    i2c_send_byte(lcd_buffer,LCD_I2C);
#ifdef DEBUGGING
    i2c_print_err();
    printf("On Write  third Data Buffer has: 0x%02X\n", lcd_buffer);
#endif
//********************************** Lower nibble*******************************
    lcd_buffer = (data & 0x0f);
    lcd_buffer <<= 4;
    lcd_buffer |= RS | LCD_BACKLIGHT;				// Lower nibble
    lcd_buffer &= ~En;
    //***************************
    i2c_send_byte(lcd_buffer,LCD_I2C);
#ifdef DEBUGGING
    i2c_print_err();
    printf("On Write  fourth Data Buffer has: 0x%02X\n", lcd_buffer);
#endif
//***********	
    lcd_buffer |= En;
    i2c_send_byte(lcd_buffer,LCD_I2C);
#ifdef DEBUGGING
    i2c_print_err();
    printf("On Write  Fifth Data Buffer has: 0x%02X\n", lcd_buffer);
#endif
//***********
    lcd_buffer &= ~En;
    i2c_send_byte(lcd_buffer,LCD_I2C);
#ifdef DEBUGGING
    i2c_print_err();
    printf("On Write  Sixth Data Buffer has: 0x%02X\n", lcd_buffer);
#endif

}

void LCDI2C_SetCursorPos(unsigned char x, unsigned char y){
short int address;

   switch(y)
     {
      case 1:
        address = LCD_LINE_1_ADDRESS;
        break;

      case 2:
        address = LCD_LINE_2_ADDRESS;
        break;

      case 3:
        address = LCD_LINE_3_ADDRESS;
        break;

      case 4:
        address = LCD_LINE_4_ADDRESS;
        break;

      default:
        address = LCD_LINE_1_ADDRESS;
        break;
     }
   address += x-1;
   LCDI2C_Write(0x80 | address , 0);
}

void LCDI2C_CursorBlink(char status){
	if (status) LCDI2C_Write(LCD_DISPLAYCONTROL | LCD_BLINKON , 0 );
	else LCDI2C_Write(LCD_DISPLAYCONTROL | LCD_BLINKOFF , 0 );
}

void LCDI2C_Putc(unsigned char c){
 switch(c)
   {
    case '\f':
      LCDI2C_Write(LCD_CLEARDISPLAY , 0);
      LCDI2C_SetCursorPos(1 , 1);
      lcd2004_line = 1;
      dly_ms(2);
      break;

    case '\n':
       LCDI2C_SetCursorPos(1 , ++lcd2004_line);
       break;

    case '\b':
       LCDI2C_Write(LCD_CURSORSHIFT|LCD_MOVELEFT,0);
       break;

    default:
       LCDI2C_Write(c,Rs);
       break;
   }
}

void LCDI2C_ReturnHome(void){
	LCDI2C_Write(LCD_RETURNHOME,0);
}

void LCDI2C_ClearDisplay(){
	LCDI2C_Write(LCD_CLEARDISPLAY,0);
	LCDI2C_ReturnHome();
}

void LCDI2C_Printrs(const MEM_MODEL char * buffer){
	while(*buffer){
		LCDI2C_Putc(*buffer++);
	}
}

void LCDI2C_Prints(char * buffer){
	while(*buffer) LCDI2C_Putc(*buffer++);
}



/*********************************************************************//**
 * @brief		Puts a decimal number to LCD until 99
 * @param[in]	decnum	Decimal number (8-bit long)
 * @return		None
 **********************************************************************/

void LCDI2C_PutDec99(uint8_t decnum)
{
    uint8_t c1 = decnum % 10;
    uint8_t c2 = (decnum / 10) % 10;
    //uint8_t c3 = (decnum / 100) % 10;
    //LCDI2C_Putc('0' + c3);
    LCDI2C_Putc('0' + c2);
    LCDI2C_Putc('0' + c1);
}


/*********************************************************************//**
 * @brief		Puts a decimal number to LCD
 * @param[in]	decnum	Decimal number (8-bit long)
 * @return		None
 **********************************************************************/

void LCDI2C_PutDec(uint8_t decnum)
{
    uint8_t c1 = decnum % 10;
    uint8_t c2 = (decnum / 10) % 10;
    uint8_t c3 = (decnum / 100) % 10;
    LCDI2C_Putc('0' + c3);
    LCDI2C_Putc('0' + c2);
    LCDI2C_Putc('0' + c1);
}

/*********************************************************************//**
 * @brief		Puts a decimal number to LCD
 * @param[in]	decnum	Decimal number (8-bit long)
 * @return		None
 **********************************************************************/

void LCDI2C_PutDec16(uint16_t decnum)
{
    uint8_t c1 = decnum % 10;
    uint8_t c2 = (decnum / 10) % 10;
    uint8_t c3 = (decnum / 100) % 10;
    uint8_t c4 = (decnum / 1000) % 10;
    uint8_t c5 = (decnum / 10000) % 10;
    LCDI2C_Putc('0' + c5);
    LCDI2C_Putc('0' + c4);
    LCDI2C_Putc('0' + c3);
    LCDI2C_Putc('0' + c2);
    LCDI2C_Putc('0' + c1);
}

/*********************************************************************//**
 * @brief		Puts a decimal number to LCD
 * @param[in]	decnum	Decimal number (8-bit long)
 * @return		None
 **********************************************************************/

void LCDI2C_PutDec32(uint32_t decnum)
{
    uint8_t c1 = decnum % 10;
    uint8_t c2 = (decnum / 10) % 10;
    uint8_t c3 = (decnum / 100) % 10;
    uint8_t c4 = (decnum / 1000) % 10;
    uint8_t c5 = (decnum / 10000) % 10;
    uint8_t c6 = (decnum / 100000) % 10;
    uint8_t c7 = (decnum / 1000000) % 10;
    uint8_t c8 = (decnum / 10000000) % 10;
    uint8_t c9 = (decnum / 100000000) % 10;
    uint8_t c10 = (decnum / 1000000000) % 10;
    LCDI2C_Putc('0' + c10);
    LCDI2C_Putc('0' + c9);
    LCDI2C_Putc('0' + c8);
    LCDI2C_Putc('0' + c7);
    LCDI2C_Putc('0' + c6);
    LCDI2C_Putc('0' + c5);
    LCDI2C_Putc('0' + c4);
    LCDI2C_Putc('0' + c3);
    LCDI2C_Putc('0' + c2);
    LCDI2C_Putc('0' + c1);
}

/*********************************************************************//**
 * @brief		Puts a hex number to LCD port without the 0x chars
 * @param[in]	hexnum	Hex number (8-bit long)
 * @return		None
 **********************************************************************/

void LCDI2C_PutHex_(uint8_t hexnum)
{
    uint8_t nibble, i;

    //UARTPuts(UARTx, "0x");
    i = 1;
    do
    {
        nibble = (hexnum >> (4 * i)) & 0x0F;
        LCDI2C_Putc((nibble > 9) ? ('A' + nibble - 10) : ('0' + nibble));
    }
    while (i--);
}

/*********************************************************************//**
 * @brief		Puts a hex number to LCD
 * @param[in]	hexnum	Hex number (8-bit long)
 * @return		None
 **********************************************************************/

void LCDI2C_PutHex(uint8_t hexnum)
{
    uint8_t nibble, i;

    LCDI2C_Prints("0x");
    i = 1;
    do
    {
        nibble = (hexnum >> (4 * i)) & 0x0F;
        LCDI2C_Putc((nibble > 9) ? ('A' + nibble - 10) : ('0' + nibble));
    }
    while (i--);
}

/*********************************************************************//**
 * @brief		Puts a hex number to LCD
 * @param[in]	hexnum	Hex number (16-bit long)
 * @return		None
 **********************************************************************/

void LCDI2C_PutHex16(uint16_t hexnum)
{
    uint8_t nibble, i;

    LCDI2C_Prints("0x");
    i = 3;
    do
    {
        nibble = (hexnum >> (4 * i)) & 0x0F;
        LCDI2C_Putc((nibble > 9) ? ('A' + nibble - 10) : ('0' + nibble));
    }
    while (i--);
}

/*********************************************************************//**
 * @brief		Puts a hex number to LCD
 * @param[in]	hexnum	Hex number (32-bit long)
 * @return		None
 **********************************************************************/

void LCDI2C_PutHex32(uint32_t hexnum)
{
    uint8_t nibble, i;

    LCDI2C_Prints("0x");
    i = 7;
    do
    {
        nibble = (hexnum >> (4 * i)) & 0x0F;
        LCDI2C_Putc((nibble > 9) ? ('A' + nibble - 10) : ('0' + nibble));
    }
    while (i--);
}
